is_project_page: false

permalink: /:title/
paginate: 5
paginate_path: "/:num/"
date_format: "%b %-d, %Y"

font-awesome-include: false
markdown: kramdown
exclude: ["README.md"]

plugins: 
  - jekyll-paginate
