plugins: 
  - jekyll-paginate
  
is_project_page: false
permalink: "/:title/"
paginate: 5
paginate_path: "/:num/"
date_format: "%b %-d, %Y"
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"


